using com.cyborgAssets.inspectorButtonPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.Profiling;

namespace BuildingGenerator
{
public class BuildingGenerator : MonoBehaviour
{
    // OBS: Uma varialvel com a ref de uma classe serializada exposta no editor "nunca" ser√° nula.
    [SerializeField] private FloorPlanGenerator _floorPlanGenerator;
    [SerializeField] private BuildingDataManager _buildingDataManager;

    int counter = 0;

    void Start()
    {
        
    }

    void Update()
    {
        
    }


    [ProButton]
    public async void GenerateBuilding()
    {
        if(!Application.isPlaying) return;

        var result = await _floorPlanGenerator.GenerateFloorPlans(_buildingDataManager.GetFloorPlanData(), 1);
        
        foreach(var plan in result)
         plan.PrintFloorPlan();
    }


    void OnDrawGizmos()
    {
        _floorPlanGenerator?.OnDrawGizmos();

        Handles.Label(transform.position, counter.ToString());
    }
}
}